import Header from "@/components/Header"
import Sidebar from "@/components/Sidebar"
import { Box, ChakraProvider, Container, Flex } from "@chakra-ui/react"

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru">
      <body>
        <ChakraProvider>
          <Header />
          <Container height={"70dvh"} maxWidth={"container.xl"} paddingY={5}>
            {children}
          </Container>
        </ChakraProvider>
      </body>
    </html>
  )
}
